### ISSUE TITLE
add ability to delete expenses

### ISSUE THREAD

**Issue by gpend** [gpend/expense_tracker#2]

**Comment by CleverlyCodes** [comment]
Hi @gpend I'm a first time contributor to open source, I'd like to contribute this fix if it's alright with you.

**Comment by gpend** [comment]
Go for it.  Have fun.

**Comment by CleverlyCodes** [comment]
@gpend thanks for letting me contribute, here are my changes: https://github.com/gpend/expense_tracker/pull/7
